[package]
name = "markov-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
clap = { version = "4.1.4", features = ["derive"] }
itertools = "0.10.5"
nalgebra = "0.32.1"
rand = "0.8.5"
rulinalg = "0.4.2"

[profile.release]
opt-level = 3
lto = true
